### PR TITLE
URGENT: Fix Blueborne (on CM 12.1)

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by minhng99** [comment]
@ishantvivek test it?

**Comment by ioanmoldovan** [comment]
I am running it on my phone right now!

**Comment by minhng99** [comment]
Okay... @ishantvivek test it on next time you build, sorry I'm no maintainer of this project.

Thanks for the PR anyway, going to test it on my device

**Comment by ishantvivek** [comment]
I am no longer supporting KYLEPROXX.

**Comment by ishantvivek** [comment]
Also, in case you commit changes, try to maintain authorship.

**Comment by ioanmoldovan** [comment]
Okay, then can you transfer ownership (can I be the maintainer?) of
github.com/Samsung-kyleproxx

**Comment by ishantvivek** [comment]
We (me and sandpox) don't even know you. You suddenly popped up kinda guy. We don't trust you. We will discuss and tell you if we want to transfer org to you or not. 
Also, by authorship i didn't mean org, i mean, try to maintain commit authorship, to whom that commit belongs too.

**Comment by ioanmoldovan** [comment]
Okay so why does it even matter who I am. You have a project that needs a
maintainer. And you're not willing to maintain it so turn it over to me
pls. (I care about the kylepro because it's my main phone)

**Comment by ishantvivek** [comment]
I don't want to be rude in anyway. 
We will discuss and get back to you. 
Indeed if anybody want to maintain it, will be supported.

**Comment by minhng99** [comment]
Okay, you now are member of this org, have fun with it and make sure to write quality codes...

Srly, if that commit is your own then go redo the kernel patch as the Linux style with driver/module name on the title and the title shouldn't have any urgent on it

If it's not your own then just git am the patch for proper author/message.

**Comment by ioanmoldovan** [comment]
Okay, will redo! Thank you, I'll try to write good code and try to fix all
the silly security bugs that Samsung will never fix :D

**Comment by TheComputerGuy96** [comment]
@ioanmoldovan Hi there

And, please don't turn into a kanger

**Comment by ioanmoldovan** [comment]
What is a kanger?

**Comment by ishantvivek** [comment]
Who pick someone's else work, and put owns name on commit author! 
E.g you

**Comment by ioanmoldovan** [comment]
IT'S MY WORK! I'm not a kanger. It was and is mine.

**Comment by ishantvivek** [comment]
https://github.com/LineageOS/android_kernel_asus_Z00D/commit/3bc8a820771c3232d8c444e0ebb1fec8d10f7bce

**Comment by ishantvivek** [comment]
Claiming don't make yours

**Comment by ioanmoldovan** [comment]
That is totally different from my patch. My patch has 1 function that
doesn't exist in his work!

**Comment by ishantvivek** [comment]
It's same, if you do your changes, first pick his change. Then put your changes on top of it, not in same commi. 
The way you're doing isn't the way thing works.
At a glance, i believe your patch is same as it. 
Show me your changes on top of the base change.

**Comment by ioanmoldovan** [comment]
How can it be the same!!!!

My patch only changes 1 file (because the other 3 don't exist in 3.4.67)

His has 4 files changed!!!

**Comment by ishantvivek** [comment]
Are you blind too, with stoopidity? 
Just check the link, i sent above^. 
You're just talking rubbish and stealing someone's else work and acting like a stoopid stubborn.

**Comment by minhng99** [comment]
^^ **merge Linux kernel into 1 module and claim it's yours**

**Comment by ishantvivek** [comment]
Nailed it 😂😂😂

**Comment by ioanmoldovan** [comment]
Yes, that would make it my version!

**Comment by ioanmoldovan** [comment]
No I'm not stealing. I'm not infridging anyone's copyright. Research
legalese!

**Comment by ioanmoldovan** [comment]
I have all legal right to do this!

**Comment by minhng99** [comment]
Really? Now we're talking legal things here? Bring it on

My org my rule, you don't have permission to do it, this is my lawn

**Comment by ioanmoldovan** [comment]
That's why I peaceably quit your org, but you continued bugging me!

**Comment by ishantvivek** [comment]
Yea you have all right, and we are not going to give a shit about what you do on your git. 
But we don't believe on kanging stuffs and don't accept kangers anyway.

**Comment by minhng99** [comment]
It's good thing that you've realised so, I guess I'll reapply your "work" with an extra space and claim it's mine... Because your version don't contain that extra space so I'm totally have all the rights to do it, right?

**Comment by ioanmoldovan** [comment]
Take for instance the GNU General Public License (despite the fact the
patch was in the public domain).

It says I'm allowed to create derivate works and to distribute them. That
means even if I change one line of comments/code it's become a new original
product (according to copyright law). Thus it is my work, and I have the
right to license it proprietary, you have no right to use my patch
according to the new license thereof.

**Comment by ioanmoldovan** [comment]
Mistake: GPL forbids relicensing, but Public Domain can be taken, NO
Questions asked.

(I've researched copyright and will use it to my benefit.)

**Comment by ioanmoldovan** [comment]
So, from now on, you're not allowed to view my file, modify my file,
reverse-engineer my file or any other thing (just like in Windows EULA,
inspiration). You can not use it in a future commit or any derivate of it.

**Comment by ishantvivek** [comment]
Since we are now close to GPL very much. Point me the exact line from where you read that?
Also, afaik you can do changes on top of it and but re-editing the original patch and removing old does'nt make you owner of that patch. 
Also, as @SandPox said go and merge whole linux kernel into 1, and go and claim @torvalds that its your.

**Comment by minhng99** [comment]
https://www.kernel.org/doc/html/v4.11/process/1.Intro.html

"Code contributed to the Linux kernel must be made available under a GPL-compatible license"

Your code must be GPL-compliance, otherwise it's not welcomed here

**Comment by ioanmoldovan** [comment]
Yes, but the Linux kernel original, this is the Samsung edition, revised
and you have no such document.

**Comment by ioanmoldovan** [comment]
* this is not the Linux kernel original

**Comment by ishantvivek** [comment]
WOW a new discovery and news that samsung made a new kernel which looks like linux but not original linux kernel. Samsung bought it from china market right?

**Comment by minhng99** [comment]
You know why Samsung must release the kernel code even though they don't want to do so? Because their product using GPL code and they must release it, otherwise their product might get banned or even sued by the license they've use even though it have their codes in there but they must make it GPL-compatible.

But the Apache license (Android platform) are different, they have all the rights to make it proprietary, that's why they don't have to release their Touchwiz source and no one can forcing them to do so.

Mediatek getting a lot of hate because they don't release their kernel code even though it must be GPL

**Comment by ioanmoldovan** [comment]
WHY CAN'T YOU LEAVE ME ALONE!!!!

**Comment by ioanmoldovan** [comment]
YOU WANT BEN ARMIS AUTHOR INSTEAD OF ME! FINE! DO IT YOURSELF!

**Comment by minhng99** [comment]
Well.. We just trying to explain why it's wrong for you to do that, also your misunderstand about GPL and Linux code license overall

**Comment by ioanmoldovan** [comment]
@Sandpox No I do NOT misunderstand it! I have all right to be AUTHOR.

**Comment by minhng99** [comment]
Okay then

Conversation over

**Comment by ishantvivek** [comment]
Eh @SandPox leave this kanger. He is stubborn foolish. 
And a ppls like him are cancer , and it can catch you too. 
A friendly warning stay away from him plox.

**Comment by ioanmoldovan** [comment]
@ishantvivek No people like you are the problem and the cause of all FOSS fails. You do NOT seem to understand how I can take a Public Domain thing (sure Linux code must be GPL-compliant, but license can't be implied, must be explicit) and make it my own through modification. You seem to think I need to heavily modify something to make it my own.

**Comment by ghost** [comment]
Bye everyone!

**Comment by dev-harsh1998** [comment]
@ioanmoldovan boi what you smoked today ?

**Comment by ioanmoldovan** [comment]
@dev-harsh1998 Nothing, this is the way I am every day. Copyright is good :D

**Comment by dev-harsh1998** [comment]
Man Man, you are smoking same thing everyday kindly quit it IMO

**Comment by ishantvivek** [comment]
Nah @ioanmoldovan i am not fool like you who thinks like that, i know how to respect someone work.
You might have problem understanding english for sure, thats why you dont understand what gpl is. 
Do a favour and go and claim that you made linux kernel by just putting a space in code.

**Comment by minhng99** [comment]
@ioanmoldovan well.. If you have confident on what you said is true then you probably won't need to delete comments

BTW, still have a backup of emails which github sending me here

**Comment by ioanmoldovan** [comment]
@ishantvivek @SandPox I read it in English, you must try to find loopholes!

**Comment by ioanmoldovan** [comment]
@ishantvivek  "i am not a fool" is correct grammar, and also you aparently don't respect MY work!

**Comment by ishantvivek** [comment]
Kangers don't get respect anywhere. So don't expect respect either from me or someone else (who do understand what gpl is).

**Comment by dev-harsh1998** [comment]
@SandPox I am an intruder can i get popcorns

**Comment by minhng99** [comment]
@dev-harsh1998 shoo, no popcorn for you

**Comment by ioanmoldovan** [comment]
@ishantvivek I AM NO KANGER. It's all fair. I did the most important piece of work! Making it work with your stupid 3.4.67 kernel!!!!!!!

**Comment by ishantvivek** [comment]
At first  you says me stupid, and in the second you says my 3.4.67 kernel? when did i made such i even dont know lol. 
First be sure to check exactly what want to write and then comment. You are confused yourself on what you are saying.

**Pull request closed without merging**
