### PR TITLE
Fuelgauge

### PR DESCRIPTION
**Pull request by omonar**
I managed to backport fuelgauge driver from android-bcm-tetra-3.10-lollipop-mr1-wear-release. It includes many improvements compared to samsung opensource version: battery capacitance dependence of temperature, introduction of battery unusuable capacity, etc.

### CODE REVIEW

**Comment by ghost** [comment]
i'll merge this into future kernel testing version, thanks

**Comment by omonar** [comment]
Just wait a litlle bit. I still need to modify kyleprods files. I will let you know when ready.

**Comment by ghost** [comment]
kyleprods source are 100% same as kylepro, i'm sure about that, just copy from kylepro and rename everything to kyleprods

**Comment by omonar** [comment]
Would be then enough to just rename board-bcm59xxx-ss-kylepro.c to board-bcm59xxx-ss-kyleprods.c?

**Comment by ghost** [comment]
inside it have some variable for kylepro, change all of them to kyleprods
you can use diffchecker.com to manual checking different between two file, there is no difference except kylepro(ds) variable and CONFIG_

**Comment by omonar** [comment]
It should be fine now and ready for testing :)

**Pull request merged**
